name: giphy_picker
description: A fast and customizable animated GIF picker for your flutter app.
version: 3.0.1
homepage: https://github.com/firstfloorsoftware/giphy_picker
screenshots:
  - description: 'Browsing trending gifs from Giphy'
    path: example/screenshots/giphy_picker_demo.gif
  - description: 'Browsing trending gifs from Giphy in dark mode'
    path: example/screenshots/giphy_picker_dark_demo.gif

environment:
  sdk: ">=2.17.6 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  assets:
    - assets/PoweredBy_200px-Black_HorizText.png
